spring:
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
      acks: all
    #      retries: 10
#      properties:
#        retry.backoff.ms: 1000
#    consumer:
#      group-id: order-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  application:
    name: service-orders

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://postgres-orders:5432/orders-db
    username: orders-user
    password: orders-password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none